/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void panel1_Click1(GPanel source, GEvent event) { //_CODE_:panel1:207187:
  println("panel1 - GPanel >> GEvent." + event + " @ " + millis());
} //_CODE_:panel1:207187:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:773265:
  appc.background(230);
} //_CODE_:window1:773265:

public void panel2_Click1(GPanel source, GEvent event) { //_CODE_:panel2:252386:
  println("panel2 - GPanel >> GEvent." + event + " @ " + millis());
} //_CODE_:panel2:252386:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.CYAN_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  panel1 = new GPanel(this, 190, 130, 100, 60, "Tab bar text");
  panel1.setText("Tab bar text");
  panel1.setOpaque(true);
  panel1.addEventHandler(this, "panel1_Click1");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 800, 400, JAVA2D);
  window1.noLoop();
  window1.addDrawHandler(this, "win_draw1");
  panel2 = new GPanel(window1, 0, 0, 300, 400, "Tab bar text");
  panel2.setText("Tab bar text");
  panel2.setOpaque(true);
  panel2.addEventHandler(this, "panel2_Click1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GPanel panel1; 
GWindow window1;
GPanel panel2; 