/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void serial_changes(GCustomSlider source, GEvent event) { //_CODE_:serial:969613:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:serial:969613:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:serialList:312105:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:serialList:312105:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.CYAN_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  serial = new GCustomSlider(this, 10, 350, 100, 40, "blue18px");
  serial.setLimits(0.0, 0.0, 1.0);
  serial.setStickToTicks(true);
  serial.setNumberFormat(G4P.EXPONENT, 0);
  serial.setOpaque(false);
  serial.addEventHandler(this, "serial_changes");
  label2 = new GLabel(this, 10, 330, 100, 30);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Serial Status");
  label2.setTextBold();
  label2.setOpaque(false);
  label3 = new GLabel(this, -20, 380, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("off");
  label3.setOpaque(false);
  label4 = new GLabel(this, 60, 380, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("on");
  label4.setOpaque(false);
  label5 = new GLabel(this, 150, 330, 80, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Serial Port");
  label5.setTextBold();
  label5.setOpaque(false);
  serialList = new GDropList(this, 150, 350, 90, 80, 3);
  serialList.setItems(loadStrings("list_312105"), 0);
  serialList.addEventHandler(this, "dropList1_click1");
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider serial; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GDropList serialList; 